version: '3'
services:
  apache2:
    build: .
    hostname: ${env:HOSTNAME}
    volumes:
      - ./etcletsencrypt:/etc/letsencrypt
      - ./varletsencrypt:/var/lib/letsencrypt
      - ./www/seniortravelbuddy:/var/www/html/seniortravelbuddy
    ports:
      - "80:80"
      - "443:443"
    environment:
      LETS_ENCRYPT_EMAIL: ${env:EMAIL}
      LETS_ENCRYPT_DOMAINS: ${env:DOMAINS}
